name: Publish NPM Package

env:
  NODE_VERSION: 16
  PKG_REGISTRY_URL: https://npm.pkg.github.com/

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test

  get-release-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/git-get-release-action@v1
        id: release
        with:
          release: ${{ github.event.release.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish-package:
    needs: get-release-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.PKG_REGISTRY_URL }}
          scope: '@redbrick'
      - run: yarn install --immutable
      - run: yarn publish --new-version ${{ steps.release.outputs.tag_name }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
